export const PRODUCT_LIST = 'PRODUCT_LIST'
export const PRODUCT_SORT_DESC = 'PRODUCT_SORT_DESC'
export const PRODUCT_SORT_ASC = 'PRODUCT_SORT_ASC'
export const PRODUCT_SORT_NAME = 'PRODUCT_SORT_NAME'
export const PRODUCT_FILTER_PRICE = 'PRODUCT_FILTER_PRICE'
export const PRODUCT_SET_CURRENCY = 'PRODUCT_SET_CURRENCY'
export const PRODUCT_ADD = 'PRODUCT_ADD'

export const USD = 0.035
export const UAH = 1

